%macro end_timer();
  data _null_; 
	  call symput('end_time', datetime()); 
  run; 
  data timer ; 
	  start = &start_time ; 
	  end = &end_time ; 
	  duration = end - start ; 
	  call symput('run_time',duration);
  run;
  title1 'total real execution time'; 
  proc print data=timer noobs; 
	  var start end duration ; 
	  format start twmdy35. end twmdy35. duration time8.; 
  run ; 
  proc sql;
  	drop table timer;
  quit;
%mend end_timer;
